/*
	Each new term in the Fibonacci sequence is generated by adding 
	the previous two terms. By starting with 1 and 2, the first 10 
	terms will be:
					1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values 
	do not exceed four million, find the sum of the even-valued terms.
*/

int FindFibonacciSequence(int max)
{
	int sum = 0;
	int currentFib = 0;
	int prevNum = 0;
	int currentNum = 1;

	while (true) 
	{
		currentFib = prevNum + currentNum;
		prevNum = currentNum;
		currentNum = currentFib;

		if (currentFib > max) {
			break;
		}

		if (currentFib % 2 == 0)
		{
			sum += currentFib;
		}
	}

	return sum;
}